### ISSUE TITLE
[FEATURE] Add option to always copy connection data right after wireless ADB is enabled

### ISSUE THREAD

**Issue by clague** [Smooth-E/wireless-adb-switch#15]
# System information

> Describe your setup, so we can understand the cause of the bug better

- Android version: Android 14
- Android vendor: One UI
- Mode: Shizuku
- WADBS version: 1.1
- Where did you get the app from: F-Droid
- Any additional information you would like to share about your system
- - KDE Connect version: 1.29.0 (From F-droid)

# Problem description

> Describe your problem with as much detail as possible. 
> You may want to include some specific conditions the problem is occurring because of in your opinion (e.g. the widget is not working, but you are using a custom home screen launcher).
> Provide error logs if you are able to get any. You can capture logs using your PC or an app such as MatLog on your Android device.

I have installed KDE Connect, and the KDE Connect integration switch in app is enabled. But when I turn on Wireless Debug using the widget or button in quick setting panel, I don't receive any clipborad sync on my PC and the script don't work too. KDE Connect's clipboard sync function is normal.

- [x] This issue was not reported before
- [x] I agree to keep the discussion polite and on point

**Comment by Smooth-E** [comment]
Hello. Since you are using Shizuku mode, commands from WADBS are ran with ADB-level privileges. In Shizuku mode, enabling the wireless debugging is done through reflection, therefore is possible. However, to run KDE Connect clipboard sync, WADBS needs to dispatch an intent to a non-exported activity. Which is not allowed with ADB shell privileges. You can check validity of my words by examining the logs of WADBS.

Recently I thougth that maybe it would be nice to maintain a small fork of KDE Connect with this needed activity marked as exported. I will not ask for this to be in upstream KDE Connect, because exporting this activity somewhat creates a security risk.

**Comment by clague** [comment]
How about just write into the clipboard?

**Comment by Smooth-E** [comment]
And I am doing this. Then I send an intent to KDE Connect so it syncs it. See this [function](https://github.com/Smooth-E/wireless-adb-switch/blob/89d317a26cb3475068ada771118e0b66ffe15b76/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/KdeConnect.kt#L29).

**Comment by clague** [comment]
I mean just copy the text when the root privilege is NOT granted. So I can use KDE Connect's send clipboard button to sync clipboard. By now, I'm just unable to get connection data copied.

**Comment by clague** [comment]
And I saw some OneUI only features in README, but I just cannot find them. Is something wrong with me or just need someone tell me where them are😂.

**Comment by Smooth-E** [comment]
> I mean just copy the text when the root privilege is NOT granted. So I can use KDE Connect's send clipboard button to sync clipboard. By now, I'm just unable to get connection data copied.

Sure, this is valid suggestion to have the data automatically put in your clipboard. Right now you can copy the connection data by tapping on an *informative* widget on your home screen or by tapping a button inside of QS Tile's *Extended menu* (One UI only).

**Comment by Smooth-E** [comment]
> And I saw some OneUI only features in README, but I just cannot find them. Is something wrong with me or just need someone tell me where them are😂.

The only One UI integration is the *Extended view* of the QS tile. This was tested on Android 11 based One UI, One UI 2.x, I believe. You can access this view by tapping the text label under the QS tile (same as if you tap *"Wi-Fi"* label under the Wi-Fi QS Tile and it opens an extended menu with some quick options and a list of networks).

**Comment by clague** [comment]
I'm in OneUI 6.0, it seems that I cannot use the QS tile feature. Only the WLAN and Bluetooth tile can be extended.

https://github.com/Smooth-E/wireless-adb-switch/assets/93119153/5bd7a82e-0726-42b8-a84f-aaf14a2f5751

**Comment by Smooth-E** [comment]
This integration was implemented through a reverse-engineered API documented by [OneUI Project](https://oneuiproject.github.io/hidden-api/qs-detail-view/). Looks like Samsung decided to change this in recent versions of OneUI. Does any of the system apps have a tile with an extended view? For example, the *Flashlight* tile had it for me. It displayed a brightness slider there.

**Comment by clague** [comment]
Yes it has. And some other system app have extended view too. And it's triggered by holding.

https://github.com/Smooth-E/wireless-adb-switch/assets/93119153/80bbaf21-1e93-4550-bedb-7e3cfeeb60d9

**Comment by Smooth-E** [comment]
Added the feature. Putting data to the clipboard is now separated from KDE Connect integration. Expect this in the next release (in a month or two).

<img width="48%" src="https://github.com/Smooth-E/wireless-adb-switch/assets/71522503/796f2e5e-3405-4858-9904-a160b6c23488"/>

<img width="48%" src="https://github.com/Smooth-E/wireless-adb-switch/assets/71522503/42544722-4eb9-42cf-b945-476c43fe2175"/>
