### ISSUE TITLE
[BUG]  Prefix connection data not doing anything

### ISSUE THREAD

**Issue by FluffyDiscord** [Smooth-E/wireless-adb-switch#18]
# System information

> Describe your setup, so we can understand the cause of the bug better

- Android version: Android 12
- Android vendor: OneUI 4.1
- Mode: Shizuku
- WADBS version: 1.1
- Where did you get the app from: GitHub Releases page
- Any additional information you would like to share about your system

# Problem description

Tapping on Connection data widget that I added on my home screen copies to clipboard only the address and port. The "Prefix connection data" does not work as it's not being appended.

- [x] This issue was not reported before
- [x] I agree to keep the discussion polite and on point

**Comment by FluffyDiscord** [comment]
Oh, yeah there might be a bit of confusion then. The adb debugging definitely did not connect to my PC when I turned the wireless debug on using the toggle widget. I did not check though if, as you say, turning on wireless adb debug using the widget also copies the connection settings to clipboard with the prefix to then just manually the clipboard content to PC using KDE connect. I will have to check it tomorrow and will report back.

This may be instead of a bug, a feature request then.

**Comment by Smooth-E** [comment]
Instant connection is achieved with toggling "Prefix connection data" and "KDE Connect integration". Then tap the *switch* widget and it should work. Though, read [scripts](https://github.com/Smooth-E/wireless-adb-switch/tree/main/scripts) first.

**Comment by FluffyDiscord** [comment]
Yes I did that and had the python script running.

**Comment by Smooth-E** [comment]
Just checked your first message. Unfortunately, KDE Connect integration requires root access for now. Switch's is modified to include [this](https://github.com/Smooth-E/wireless-adb-switch/commit/e0240bfdef85d77eca0642e0f80ebc1124cdbb31) information with this commit (will be out in the next release). You can also check out #15

**Comment by FluffyDiscord** [comment]
Yes haha, it makes sense now. I am closing this issue, since it's kind of duplicate.
