### ISSUE TITLE
Shizuku mode

### ISSUE THREAD

**Issue by Alistair1231** [Smooth-E/wireless-adb-switch#2]
Nothing happens when I press the quick tile or widget.
I'm on Lineage OS 20 (Android 13) and I am not rooted.

**Comment by Smooth-E** [comment]
It is impossible to [change the state of the Wireless Debugging feature](https://github.com/Smooth-E/wireless-adb-switch/blob/dcaab5e3da7af3bbac92e63075fffbf40ecb336c/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/WirelessDebugging.kt#L22) without the root access. <br> It is also impossible to trigger KDE Connect's Clipboard Sharing feature from a different app without [launching an Intent](https://github.com/Smooth-E/wireless-adb-switch/blob/dcaab5e3da7af3bbac92e63075fffbf40ecb336c/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/KdeConnect.kt#L35) to an Activity which is [marked as not exported](https://github.com/Smooth-E/wireless-adb-switch/blob/dcaab5e3da7af3bbac92e63075fffbf40ecb336c/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/KdeConnect.kt#L35).

Perhaps, I should probably state this in both the README and the fastlane description.

I had plans to look into what [Shizuku](https://shizuku.rikka.app/) may provide as an alternative to root. If I will be able to make WADBS work without root but with Shizuku, it will be stated in both the README and the fastlane description, after I release the version with such capability.

This issue will remain open until I modify the README and the description of WADBS accordingly.

Thanks for reporting!

**Comment by Alistair1231** [comment]
Ah yeah a shizuku method might work, or maybe opening the wifi debug setting for the user to simply tap to enable it?
Looking forward to it.
And I concur it should probably give a warning message that root is required, as well as state that in the description.

**Comment by Smooth-E** [comment]
Okay, no need to do so. After reading [this](https://stackoverflow.com/a/59378575), it turns out I need the `INTERACT_ACROSS_USERS` permission to execute `settings get global adb_wifi_enabled`. I should probably read more about Shizuku, as it executes with the privileges of ADB, which are enough for `settings get`. In Shizuku mode (if it will work) the app will have no Instant connection feature and the Informative widget will be useless. So, it will only be doing what's mentioned in the name - act as a switch.

**Comment by Terkyz** [comment]
Is there any update on this? Maybe I'm doing something wrong but in my case the app doesn't really do anything? The "Enable debugging" widget does nothing and as the description says I have to press and hold it to enter WADBS, and once there I don't see what I can do apart from activating KDE Connect integration and the "Prefix synced connection data" option.

When I click on the arrow to go back to the menu inside the settings from the widget the app closes without any information and I can't do anything.

**Comment by Smooth-E** [comment]
> Is there any update on this? Maybe I'm doing something wrong but in my case the app doesn't really do anything? The "Enable debugging" widget does nothing and as the description says I have to press and hold it to enter WADBS, and once there I don't see what I can do apart from activating KDE Connect integration and the "Prefix synced connection data" option.
> 
> When I click on the arrow to go back to the menu inside the settings from the widget the app closes without any information and I can't do anything.
> 
> Edit: Neither the tray icon or the widget seems to work.

Hello @Terkyz! 

First of all, this issue is not abandoned. I have recently implemented support for Shizuku. I will release a new version with such support in a couple of weeks. The only thing left before this is to prepare some promo materials and do some extra debugging.

Second, the latest release of WADBS as of now (if you got it from IzzyOnDroid or GitHub releases) requires root access to work. I did not implement any notification or error message back then, so this is why you don't see anything other than just a non-working app.

**Comment by Alistair1231** [comment]
> Hey there, @Alistair1231 ! I am now continuing my work on WADBS and am calling out for testing. I've investigated what Shizuku can do and realized that is just a faster framework for root access and command execution. Therefore, on non-rooted devices it will only give access to thing an ADB shell can do, nothing more than that (well, as far as I understood).
> 
> I would like to invite you to test some functionality on your device. Please, run the following commands inside your `adb shell`, without elevating the privileges to the root level. Note that your shell should display a `$` dollar sign in the beginning and not a `#` hashtag.

Hi. I'm very sorry, I missed the notification. I'd be happy to help. Here are the results, this is on a pixel 8 running Android 14:

> The following should return either 0 or 1, depending on whether you have Wireless Debugging enabled or not.
> 
> ```shell
> settings get global adb_wifi_enabled
> ```

`settings get global adb_wifi_enabled` does work, with only usb debugging it shows 0 and when I turn on wireless debugging it show 1

> The following should turn Wireless Debugging on or off, depending on whether you put 1 or 0 instead of `<state>`. I expect it to not work on non-rooted devices.
> 
> ```shell
> settings put global adb_wifi_enabled <state>
> ```
> 

Wow, this also works! 

> Running the following command with Wireless Debugging enabled should return the port number needed to establish the connection. It most likely will not work on non-rooted devices.
> 
> ```shell
> getprop service.adb.tls.port
> ```
> 

Yeah, this one gives an empty response, unfortunately.

> With KDE Connect installed (both Play Store and F-Droid versions will do) running the following command will display a toast and exchange the clipboard with a connected device. I do not expect it to work on non-rooted devices because we are launching an activity which is not exported.
> 
> ```shell
> am start -n org.kde.kdeconnect_tp/org.kde.kdeconnect.Plugins.ClibpoardPlugin.ClipboardFloatingActivity --ez SHOW_TOAST 1
> ```
> 

I get this error:
```
Starting: Intent { cmp=org.kde.kdeconnect_tp/org.kde.kdeconnect.Plugins.ClibpoardPlugin.ClipboardFloatingActivity (has extras) }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=org.kde.kdeconnect_tp/org.kde.kdeconnect.Plugins.ClibpoardPlugin.ClipboardFloatingActivity (has extras) } from null (pid=19360, uid=2000) not exported from uid 10299
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1136)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1069)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:742)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1288)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1239)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3232)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:724)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:233)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9681)
        at android.os.Binder.shellCommand(Binder.java:1068)
        at android.os.Binder.onTransact(Binder.java:888)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5267)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
        at android.os.Binder.execTransactInternal(Binder.java:1344)
        at android.os.Binder.execTransact(Binder.java:1275)
```
I thought it might be related to missing "draw over other apps" permission, but it still gives the error. Just to be sure, I used Shizuku and aShell to run it on the phone directly instead of the terminal on my pc like the other times, no difference.

> Decided to ask you for help because on my own device ADB starts as root immediately and on Android Studio's emulators privileges might be somewhat elevated.
> 
> Thank you in advance!

**Comment by Smooth-E** [comment]
Hello again, @Alistair1231! I have done some testing myself, and with Shizuku WADBS is able to get the `service.adb.tls.port` property as well.

> I thought it might be related to missing "draw over other apps" permission, but it still gives the error. Just to be sure, I used Shizuku and aShell to run it on the phone directly instead of the terminal on my pc like the other times, no difference.

As for the intent to KDE Connect, it is not dependent on any permission. The problem here is that an activity WADBS sends an intent to is marked as `exported=false`, meaning that it is [not accessible to other apps](https://developer.android.com/privacy-and-security/risks/android-exported#overview). With `su` (root access) this Manifest property is ignored. You can see how it is implemented in WADBS [here](https://github.com/Smooth-E/wireless-adb-switch/blob/50acfd2d2a03939a0043f73c460a080848194be8/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/KdeConnect.kt#L30C9-L30C9).

As it was said before, Shizuku integration will be available soon and it will support everything apart from KDE Connect integration.

**Comment by Alistair1231** [comment]
Oh sweet! I just hate how much of a hassle rooting is nowadays. Half the apps don't work, and it's an endless, complicated cat-and-mouse game to circumvent it. 
That's why I just don't do it anymore. Love seeing that WADBS is being updated to allow non-root usage!

How did you get the port? In the code I still see only see this
```
fun getPort(context: Context): String {
        val command = "getprop service.adb.tls.port"
        val result = executeShellCommand(context, command)

        if (result == null || !result.isSuccess)
            throw Exception("Failed to obtain wireless debugging port!")

        return result.out.joinToString("\n")
    }
```
and even running in aShell using Shizuku that gives me an empty response.

On F-Droid and in the releases I still see WADBS 1.0.0, so the actual update is still being worked on?

Also, would it make a difference if I used KDE Connect from F-Droid?

**Comment by Alistair1231** [comment]
> Uhhh... Looks like I forgot that on my device adb starts with root access granted. Because testing it now on an emulator reveals that getprop service.adb.tls.port returns an empty string. Will have to either find a workaround or add some extra messages about this to the app. 

Maybe inspiration can be taken from the shizuku pairing process? I don't understand how it works, but it seems to only ask for the pairing code and not the port.

> But then the usefulness of the app becomes questionable without the port data.

Even that would be helpful for me, as I could then enable it using WADBS and afterwards open LADB to set my port to 5555, like this: https://www.macrodroidforum.com/index.php?threads/wifi-adb-debug-mode-lost-on-restart.1273/post-24654

Considering it takes a while for LADB to connect, I assume it just tries all the ports until it finds the correct one to connect to? That is a pure guess, but it takes a bit to connect and you only pair it once. Afterwards it just wants you to have Wireless Debugging activated.
LADB is a paid application, so I doubt it will be easy to find out how it works..

**Comment by Smooth-E** [comment]
Quick update on this feature request. I've been investing Android's source and how to use Shizuku's APIs for the last couple of days, and today I managed to set / get the state of Wireless ADB and get the port with root-less Shizuku on an (unmodified) Android emulator. You can expect these features to land in approximately two weeks in the next WADBS release, if everything goes well.

**Comment by Smooth-E** [comment]
WADBS 1.1 is out and brings Shizuku mode to the app!

**Comment by Terkyz** [comment]
I have a question, I haven't tried it yet and as soon as I can I will but I was thinking something and maybe I'm wrong, but to use Shizuku I need to activate debug mode, the app (I guess) strictly needs to have Shizuku running or is it enough to give it permission? Because then WADBS would only serve to turn off the developer mode, since it could not be turned on because Shizuku is no longer running, right? 

Edit: Just tried and if I have Shizuku running and use WADBS to turn off debug mode I can no longer turn it back on from WADBS because logically since Shizuku is not running, it no longer has access to Shizuku.

**Comment by Smooth-E** [comment]
You are correct. To use WADBS in Shizuku mode you will have to activate Shizuku using a PC. [This method](https://shizuku.rikka.app/guide/setup/#start-by-connecting-to-a-computer) is what I used during testing.

Unfortunately if you activate Shizuku through wireless debugging, then you have to keep wireless debugging enabled for it to continue working. Shizuku mode brings an ability to use WADBS on non-rooted devices, however it has some limitations.
