### ISSUE TITLE
Question - Intent parameters

### ISSUE THREAD

**Issue by chaoscreater** [Smooth-E/wireless-adb-switch#23]
Hi there,

I came across your app and wondering if you can help me. I'm trying to figure out the Android intent to open the Wireless Debugging page directly. I use MacroDroid and I can use an action to send an intent. Once I get to the Wireless Debugging page, I can then use MacroDroid to do some automations. I can't figure out what the intent parameters are though, I've looked online and just couldn't find this.

Alternatively, does your app support Tasker? I can run Tasker plugins with MacroDroid and all I need is to get the IP address and the port shown on the Wireless Debugging page.

**Comment by Smooth-E** [comment]
Hello! My app is mostly based on using commands to get the data it needs. In Shizuku mode, some features use Java reflection APIs to access system-hidden features. 

I used MacroDroid a very long time ago. Can you run commands there? Even if you can, you will need root privileges for these commands to take effect. I can list out the commands here, if you still need them.

> Does your app support Tasker?

No, not directly. I can think of making an integration, though. Unfortunately, right now widgets are executing code directly (not by sending intents to some other components), thus there is no way to use Tasker with such intents.

I remember Tasker being a paid app. Do they have docs for creating integrations?

**Comment by chaoscreater** [comment]
Hey thanks for your reply.

In MacroDroid, you can create actions. Some actions are very simple, such as Enable Wifi, while some are a bit more complex. There's an action called Send Intent and in this action, we can define a few parameters. For example, I can use the following to open the Developer Settings page:

![image](https://github.com/Smooth-E/wireless-adb-switch/assets/18227319/ecb24723-193b-4ca8-9285-33f5c241e276)

Note that some of the data shown in the Extra fields is a bit long and got cut off. There are multiple extra fields that I can use, up to 6 of them.

As for Tasker, it's very similar to MacroDroid and most of the Tasker plugins are supported directly by MacroDroid. I only know about the Tasker plugins from an end-user's perspective, not from a dev's perspective. I found this, not sure if it helps:
https://tasker.joaoapps.com/pluginslibrary.html

**Comment by Smooth-E** [comment]
> Hello! My app is mostly based on using commands to get the data it needs. In Shizuku mode, some features use Java reflection APIs to access system-hidden features.
> 
> I used MacroDroid a very long time ago. Can you run commands there? Even if you can, you will need root privileges for these commands to take effect. I can list out the commands here, if you still need them.
> 
> > Does your app support Tasker?
> 
> No, not directly. I can think of making an integration, though. Unfortunately, right now widgets are executing code directly (not by sending intents to some other components), thus there is no way to use Tasker with such intents.
> 
> I remember Tasker being a paid app. Do they have docs for creating integrations?

Looked at [MacroDroid's plugins page](https://macrodroidforum.com/wiki/index.php/Plugins) and seems it can execute commands using some of them (Termux:Tasker, ADB Shell [Tasker plugin]). If you have root, here are the commands you have to execute:

**Check if wireless debugging is enabled** (returns 1 or 0):
```sh
settings get global adb_wifi_enabled
```

**Enable / disable wireless debugging** (`$state` is whether 1 or 0):
```sh
settings put --user current global adb_wifi_enabled $state
```

This is how you can get the port wireless debugging is using:
```sh
getprop service.adb.tls.port
```

To get your IP address, you can use `ip address show` from the `iproute2` Termux package with some other options.

**Comment by Smooth-E** [comment]
> Replying to [your message regarding MacroDroid actions](https://github.com/Smooth-E/wireless-adb-switch/issues/23#issuecomment-2051207978)

My application does not have any intents, exported or not, that are able to modify the state of wireless debugging. Adding a broadcast receiver that will receive something like `app.wadbs.ENABLE_DEBUGGING` to change the state may be useful, though, I agree.

What bothers me a little, is how it affects the security of your device. If those intents are exported, it means that any app can change the state of wireless ADB which is a serious vector of attack (even though, Android will display a popup if you enable wireless debugging on a foreign network).

Security concerns are also the reason I will not ask KDE Connect to export its *SHARE CLIPBOARD* intent.

**Comment by chaoscreater** [comment]
Yes, I have root and I'm actually using adb_wifi_enabled already. I can turn on Wireless Debugging on/off by using that. Actually, MacroDroid has a helper app that is built against an older Android SDK and that means we can also use ADB to get additional functionalities, without necessarily using root. I can use either root or ADB on my phone.

As you can see below, adb_wifi_enabled is set to true. I can see it being enabled in the Wireless Debugging page as well:

![image](https://github.com/Smooth-E/wireless-adb-switch/assets/18227319/72741bda-f8a5-4a2b-8523-64ee4760290c)

However, getprop service.adb.tls.port returns nothing.

I think I found the port though, I used getprop service.adb.**tcp**.port instead:

![image](https://github.com/Smooth-E/wireless-adb-switch/assets/18227319/03c87814-81fc-4c6b-8bab-3e7587615e2e)

**Comment by Smooth-E** [comment]
Commands above are the ones I use inside WADBS. I was struggling to enable wireless debugging using `settings set ...`, because app-level privileges are not enough. ADB-level privileges are enough, so I use a UserService to execute a command in Shizuku mode ([permalink](https://github.com/Smooth-E/wireless-adb-switch/blob/e0240bfdef85d77eca0642e0f80ebc1124cdbb31/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/WirelessDebugging.kt#L23)).

Regarding acquiring the port. The `getprop service.adb.tls.port` requires root and for Shizuku mode, I am using UserService's reflection capabilities to get it through a hidden API ([permalink](https://github.com/Smooth-E/wireless-adb-switch/blob/e0240bfdef85d77eca0642e0f80ebc1124cdbb31/app/src/main/java/com/smoothie/wirelessDebuggingSwitch/UserService.java#L66)).

**Comment by Smooth-E** [comment]
Since I listed all of the commands and you have found some yourself, I consider this issue to be solved. Should you have any additional questions, feel free to reopen it. Thanks for being interested in WADBS
