### ISSUE TITLE
Crashes on Start (Android 14 / not rooted)

### ISSUE THREAD

**Issue by Alistair1231** [Smooth-E/wireless-adb-switch#4]
Hi! I thought I should put this in it's own issue.
When I start WADBS (from F-Droid) it simply crashes without dissplaying anything. I tried to capture the logcat output while starting it and then fished around there, using the app name, for some interesting results.
 I don't know if there is sensitive data in there and it's over 2 MiB for a few seconds so I don't want to publish it all.

<details><summary>here are some one-off lines</summary>

```
10-19 10:24:19.121  1562  1739 V BackupManagerService: [UserID:0] restoreAtInstall pkg=com.smoothie.wirelessDebuggingSwitch token=aa restoreSet=368486ab6c8c17b9
10-19 10:24:23.010  1562  1739 I AppsFilter: interaction: PackageSetting{81dc161 com.google.android.microdroid.empty_payload/10246} -> PackageSetting{75bd849 com.smoothie.wirelessDebuggingSwitch/10377} BLOCKED
10-19 10:24:23.462  1562  1562 I NotificationService: Cannot find enqueued record for key: 0|com.looker.droidify|3|download-com.smoothie.wirelessDebuggingSwitch|10368
10-19 10:24:24.540  1562  1685 D AppWidgetServiceImpl: Provider info from ComponentInfo{com.smoothie.wirelessDebuggingSwitch/com.smoothie.wirelessDebuggingSwitch.widget.BasicWidget} won't be persisted.
10-19 10:24:24.540  1562  1685 D AppWidgetServiceImpl: Provider info from ComponentInfo{com.smoothie.wirelessDebuggingSwitch/com.smoothie.wirelessDebuggingSwitch.widget.InformationWidget} won't be persisted.
10-19 10:24:26.102  1562  4930 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.smoothie.wirelessDebuggingSwitch/.SettingsActivity} with LAUNCH_MULTIPLE from uid 10368 (BAL_ALLOW_VISIBLE_WINDOW) result code=0
10-19 10:24:26.120  1562  1687 I ActivityManager: Start proc 26418:com.smoothie.wirelessDebuggingSwitch/u0a377 for next-top-activity {com.smoothie.wirelessDebuggingSwitch/com.smoothie.wirelessDebuggingSwitch.SettingsActivity}
10-19 10:24:26.129  1562  4930 D CoreBackPreview: Window{2ff0ac1 u0 Splash Screen com.smoothie.wirelessDebuggingSwitch}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@dd76ef2, mPriority=0, mIsAnimationCallback=false}
10-19 10:24:26.143  1562  1666 V WindowManager:     info={id=684 t=OPEN f=0x0 trk=0 r=[0@Point(0, 0)] c=[{WCT{RemoteToken{1f950f9 Task{6f0ab8d #91 type=standard A=10377:com.smoothie.wirelessDebuggingSwitch}}} m=OPEN f=NONE leash=Surface(name=Task=91)/@0x9b42943 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{WCT{RemoteToken{d059263 Task{dc62673 #82 type=standard A=10368:com.looker.droidify}}} m=TO_BACK f=NONE leash=Surface(name=Task=82)/@0x9e24e1d sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
```
</details>

and then here is something that looks promising (too large for the issue): https://paste.sh/dFqU4-L_#nzORwAC2zJIs19lhfW6iWIwc

**Comment by Smooth-E** [comment]
> and then here is something that looks promising

Yeah, this is the issue.

Android 13 [requires](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms) an additional permission to set exact alarms. They are used to update widgets and to not create a background service, because this will require a permanent notification, which is annoying. Now I know that blindly increasing the `targetSdk` can cause problems 😅 

This permission was [added to the manifest](https://github.com/Smooth-E/wireless-adb-switch/blob/173ec5653789eb7cb1ddaf598ba8ef00a99b3b67/app/src/main/AndroidManifest.xml#L9), so everything should be all good in the next release.

For your interest, [this](https://stackoverflow.com/a/39298134) is how you can filter out logs (usually by package name).

This issue will remain open before the release.

**Comment by Alistair1231** [comment]
> > and then here is something that looks promising
> 
> Yeah, this is the issue.
> 
> Android 13 [requires](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms) an additional permission to set exact alarms. They are used to update widgets and to not create a background service, because this will require a permanent notification, which is annoying. Now I know that blindly increasing the `targetSdk` can cause problems 😅
> 
> This permission was [added to the manifest](https://github.com/Smooth-E/wireless-adb-switch/blob/173ec5653789eb7cb1ddaf598ba8ef00a99b3b67/app/src/main/AndroidManifest.xml#L9), so everything should be all good in the next release.
> 
> For your interest, [this](https://stackoverflow.com/a/39298134) is how you can filter out logs (usually by package name).
> 
> This issue will remain open before the release.

Ah perfect! I considered using grep, but then the actual error would be missing, wouldn't it? Since I would only get the lines that contained the package name. Like here, I would only get the lines in pink
![image](https://github.com/Smooth-E/wireless-adb-switch/assets/26165288/d920dc17-db97-4c1b-9e5e-c9f1655bbd89)

And the PID is different every time it launches, isn't it?

**Comment by Smooth-E** [comment]
WADBS v1.1 is now out and this issue is fixed there!
